/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchedRouteImport } from './routes/matched'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsIdIndexRouteImport } from './routes/jobs.$id.index'
import { Route as JobsIdApplyRouteImport } from './routes/jobs.$id.apply'
import { Route as JobsIdEditRouteImport } from './routes/jobs.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchedRoute = MatchedRouteImport.update({
  id: '/matched',
  path: '/matched',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdIndexRoute = JobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsIdRoute,
} as any)
const JobsIdApplyRoute = JobsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsIdRoute,
} as any)
const JobsIdEditRoute = JobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matched': typeof MatchedRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/jobs/$id/edit': typeof JobsIdEditRoute
  '/jobs/$id/': typeof JobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matched': typeof MatchedRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/jobs/new': typeof JobsNewRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/jobs/$id/edit': typeof JobsIdEditRoute
  '/jobs/$id': typeof JobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matched': typeof MatchedRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/jobs/$id/edit': typeof JobsIdEditRoute
  '/jobs/$id/': typeof JobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/dashboard'
    | '/login'
    | '/matched'
    | '/profile'
    | '/register'
    | '/saved'
    | '/jobs/$id'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$id/apply'
    | '/jobs/$id/edit'
    | '/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/dashboard'
    | '/login'
    | '/matched'
    | '/profile'
    | '/register'
    | '/saved'
    | '/jobs/new'
    | '/jobs'
    | '/jobs/$id/apply'
    | '/jobs/$id/edit'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/dashboard'
    | '/login'
    | '/matched'
    | '/profile'
    | '/register'
    | '/saved'
    | '/jobs/$id'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$id/apply'
    | '/jobs/$id/edit'
    | '/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MatchedRoute: typeof MatchedRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  JobsIdRoute: typeof JobsIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matched': {
      id: '/matched'
      path: '/matched'
      fullPath: '/matched'
      preLoaderRoute: typeof MatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id/': {
      id: '/jobs/$id/'
      path: '/'
      fullPath: '/jobs/$id/'
      preLoaderRoute: typeof JobsIdIndexRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/jobs/$id/apply': {
      id: '/jobs/$id/apply'
      path: '/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof JobsIdApplyRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/jobs/$id/edit': {
      id: '/jobs/$id/edit'
      path: '/edit'
      fullPath: '/jobs/$id/edit'
      preLoaderRoute: typeof JobsIdEditRouteImport
      parentRoute: typeof JobsIdRoute
    }
  }
}

interface JobsIdRouteChildren {
  JobsIdApplyRoute: typeof JobsIdApplyRoute
  JobsIdEditRoute: typeof JobsIdEditRoute
  JobsIdIndexRoute: typeof JobsIdIndexRoute
}

const JobsIdRouteChildren: JobsIdRouteChildren = {
  JobsIdApplyRoute: JobsIdApplyRoute,
  JobsIdEditRoute: JobsIdEditRoute,
  JobsIdIndexRoute: JobsIdIndexRoute,
}

const JobsIdRouteWithChildren =
  JobsIdRoute._addFileChildren(JobsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MatchedRoute: MatchedRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  JobsIdRoute: JobsIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
